AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yapp-challenge-app

  Sample SAM Template for yapp-challenge-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MoviesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetMovies
      Description: Get all movies into DB
      CodeUri: ms-movies/
      Handler: getMovies.lambdaHandler
      Runtime: nodejs12.x
      # Environment:
      #   Variables:
      #     DB_NAME: yapp-app
      #     DB_USER: yapp-user-challenge
      #     DB_PASWORD: yappChallenge
      #     DB_HOST: 127.0.0.1
      #     DB_PORT: 8889
      Events:
        GetMoviesApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getMovies
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetMoviesApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getMovies/"
  MoviesFunction:
    Description: "Get all movies Function ARN"
    Value: !GetAtt GetMoviesFunction.Arn
